version: '3.8'

services:
  scheduler:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: rzd-scheduler
    build:
      context: .
      dockerfile: 'RZD.Scheduler/Dockerfile'
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - network

  db:
    image: postgres:17.4
    container_name: rzd-db
    env_file:
      - .env
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network

volumes:
  pgdata:
    driver: local

networks:
  network:
    driver: bridge
