version: '3.8'

services:
  scheduler:
    container_name: rzd-scheduler
    build:
      context: .
      dockerfile: 'RZD.Scheduler/Dockerfile'
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped  

  api:
    container_name: rzd-api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: 'RZD.Api/Dockerfile'
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped  

  front:
    container_name: rzd-front
    build:
      context: .
      dockerfile: 'rzd.front/Dockerfile'
    depends_on:
      - api
    env_file:
      - .env
    restart: unless-stopped  

  db:
    image: postgres:17.4
    container_name: rzd-db
    env_file:
      - .env
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped  

  nginx:
    container_name: rzd-nginx
    image: nginx:latest
    depends_on:
      - api
      - front
    ports:
      - 8000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped  

volumes:
  pgdata:
    driver: local
