version: '3.8'

services:
  scheduler:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: rzd-scheduler
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17.4
    container_name: rzd-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local