version: '3.8'

services:
  scheduler:
    container_name: rzd-scheduler
    build:
      context: .
      dockerfile: 'RZD.Scheduler/Dockerfile'
    depends_on:
      - db
    env_file:
      - .env

  api:
    container_name: rzd-api
    ports:
      - "8080:8080"
    build:
        context: .
        dockerfile: 'RZD.Api/Dockerfile'
    env_file:
        - .env


  db:
    image: postgres:17.4
    container_name: rzd-db
    env_file:
      - .env
    ports:
      - "6543:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
    driver: local
